Models/DB/EstablecimientoDeSalud.cs
using System;
using System.Collections.Generic;

namespace BBT_Plataforma_Establecimientos_De_Salud.Models.DB;

public partial class EstablecimientoDeSalud
{
    public int Id { get; set; }

    public int CodigoRenaes { get; set; }

    public string Nombre { get; set; } = null!;

    public string Ciudad { get; set; } = null!;

    public string Red { get; set; } = null!;

    public string Direccion { get; set; } = null!;

    public decimal Longitud { get; set; }

    public decimal Latitud { get; set; }

    public string? Descripcion { get; set; }

    public string? Imagen { get; set; }

    public virtual ICollection<Busquedum> Busqueda { get; set; } = new List<Busquedum>();

    public virtual ICollection<Valoracion> Valoracions { get; set; } = new List<Valoracion>();
    //Metodos
    public List<EstablecimientoDeSalud> Buscar(string criterio)
    {
        List<EstablecimientoDeSalud> ListEst = new List<EstablecimientoDeSalud>();
        try
        {
            using (var db = new Models.DB.BbtEstablecimientosDeSaludContext())
            {
                var EstSalud = from datos in db.EstablecimientoDeSaluds select datos;
                ListEst = EstSalud.Where(e => e.Nombre.Contains(criterio)).ToList();
            }
        }
        catch (Exception ex)
        {
            throw;
        }
        return ListEst;
    }
    public EstablecimientoDeSalud BuscarId (int EstId)
    {
        EstablecimientoDeSalud objEst = new EstablecimientoDeSalud();
        try
        {
            using (var db = new Models.DB.BbtEstablecimientosDeSaludContext())
            {
                var EstSalud = from datos in db.EstablecimientoDeSaluds select datos;
                objEst = EstSalud.Where(e => e.Id == EstId).FirstOrDefault();
            }
        }
        catch (Exception ex)
        {
            throw;
        }
        return objEst;
    }
    public List<EstablecimientoDeSalud> Listar()
    {
        List<EstablecimientoDeSalud> objEst = new List<EstablecimientoDeSalud>();
        try
        {
            using (var db = new Models.DB.BbtEstablecimientosDeSaludContext())
            {
                var EstSalud = from datos in db.EstablecimientoDeSaluds select datos;
                objEst = EstSalud.ToList();
            }
        }
        catch (Exception ex)
        {
            throw;
        }
        return objEst;
    }
}

ViewModels/EstablecimientoDeSaludViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BBT_Plataforma_Establecimientos_De_Salud.Models;
using BBT_Plataforma_Establecimientos_De_Salud.Models.DB;

namespace BBT_Plataforma_Establecimientos_De_Salud.ViewModel
{
    public class EstablecimientoDeSaludViewModel
    {
        public EstablecimientoDeSalud estSalud { get; set; }
        public Valoracion valoracion { get; set; }
        public List<Valoracion> listValoracion { get; set; }
        public int TotalValoraciones { get; set; }
    }
}

Controllers/EstablecimientoDeSaludController.cs
using Microsoft.AspNetCore.Mvc;
using BBT_Plataforma_Establecimientos_De_Salud.Models.DB;
using BBT_Plataforma_Establecimientos_De_Salud.ViewModel;

namespace BBT_Plataforma_Establecimientos_De_Salud.Controllers
{
    public class EstablecimientoDeSaludController : Controller
    {
        EstablecimientoDeSalud Est = new EstablecimientoDeSalud();
        public IActionResult Buscar(string criterio)
        {
            EstablecimientoDeSalud objEst = new EstablecimientoDeSalud();
            var listEst = objEst.Buscar(criterio);
            return View(listEst);
        }
        public IActionResult Detalle(int EstId)
        {
            EstablecimientoDeSalud objEst = new EstablecimientoDeSalud();
            EstablecimientoDeSaludViewModel objEstvm = new EstablecimientoDeSaludViewModel();
            Valoracion objVal = new Valoracion();
            var IdEst = objEst.BuscarId(EstId);
            objEstvm.estSalud = IdEst;
            objEstvm.valoracion = objVal.BuscarId(IdEst.Id);
            objEstvm.listValoracion = objVal.ListarId(IdEst.Id);
            objEstvm.TotalValoraciones = (objEstvm.listValoracion.Count() == 0) ? 0 : Convert.ToInt32(objEstvm.listValoracion.Sum(x => x.Valoracion1) / objEstvm.listValoracion.Count());
            return View(objEstvm);
        }
        [HttpPost]
        public IActionResult Valorar(Valoracion objVal)
        {

            objVal.Guardar();
            return RedirectToAction("Detalle", new { EstId = objVal.EstablecimientoId }); ;
        }
    }
}

Views/EstablecimientoDeSalud/Buscar.cshtml
@model List<BBT_Plataforma_Establecimientos_De_Salud.Models.DB.EstablecimientoDeSalud>;
@{
    ViewData["Title"] = "Buscar";
}
<div id="Resultados" class="container bg-light align-self-center">
    <h1 class="align-self-center text-primary fw-bold text-center">RESULTADOS</h1>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-4">
                <div class="card">
                    <img class="card-img-top" src="https://via.placeholder.com/150" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">@item.Nombre</h5>
                        <p class="card-text">@item.Descripcion</p>
                        @using (Html.BeginForm("Detalle", "EstablecimientoDeSalud", FormMethod.Post))
                        {
                            @Html.TextBox("EstId", item.Id, new { @class = "form-control me-2 bg-light rounded-pill", aria_label = "Buscar", type = "hidden"})
                            <div class="d-flex">
                                <button type="submit" class="btn btn-info">Ver Detalles</button>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <br />
        }
    </div>
</div>

Views/EstablecimientoDeSalud/Detalle.cshtml
@model BBT_Plataforma_Establecimientos_De_Salud.ViewModel.EstablecimientoDeSaludViewModel;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Detalle";
}
@section scripts{
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script>
        // Inicializar y añadir el mapa
        function initMap() {
            // La localizacion de Tacna
            const estS = {
                lat: @Html.Raw(Model.estSalud.Latitud.ToString().Replace(',', '.')),
                lng: @Html.Raw(Model.estSalud.Longitud.ToString().Replace(',', '.'))
            };
            // El mapa centrado en Tacna
            const map = new google.maps.Map(document.getElementById("map"), {
                zoom: 15,
                center: estS,
            });
            // El marcador, posicionado en el establecimiento de Salud
            const marker = new google.maps.Marker({
                position: estS,
                map: map,
            });
        }

        window.initMap = initMap;
    </script>
}
@section style {
    <style>
        #map {
            width: 50%;
            height: 50vh
        }
    </style>
}
@section scriptsBody{
    <!-- Script para llamar a la API de Google Maps -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDbRC-cA8A-wCyTJoPe2wLtOk1_9aPzVCA&callback=initMap&v=weekly"
            defer></script>
}
<div class="container bg-light align-self-center">
    <h1 class="align-self-center text-primary fw-bold text-center">@Model.estSalud.Nombre</h1>
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div>
                    <input id="input-21e" value="@Model.TotalValoraciones" type="text" class="rating" data-theme="krajee-fas" data-min=0 data-max=5 data-step=0.5 data-size="xs" title="" disabled>
                </div>
                <img class="card-img-top" src="https://via.placeholder.com/150" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">@Model.estSalud.Nombre</h5>
                    <p class="card-text">@Model.estSalud.Descripcion</p>
                    <p class="card-text">@Model.estSalud.Direccion</p>
                </div>
            </div>
        </div>
        <div id="map" class="col-md-4"></div>
    </div>
</div>
@if (HttpContextAccessor.HttpContext.Session.GetString("UsuarioNombre") != null)
{
    
    <div id="comments-section" class="container bg-light align-self-center">
        <h5 class="text-black-50 fw-bold">Agrega tu valoración</h5>
        @using (Html.BeginForm("Valorar", "EstablecimientoDeSalud", FormMethod.Post))
        {
            @Html.TextBox("Valoracion1", null, new { @class = "rating", @type = "number", data_theme = "krajee-fas", data_min = 0, data_max = 5, data_step = 1, data_size = "xs", @title = "" })
            <label for="name-input">@HttpContextAccessor.HttpContext.Session.GetString("UsuarioNombre")</label>
            @Html.TextBox("UsuarioId", HttpContextAccessor.HttpContext.Session.GetString("UsuarioId"), new { type = "hidden"})
            @Html.TextBox("EstablecimientoId", Model.estSalud.Id, new { type = "hidden"})
            @Html.TextArea("Comentario", null, new { @class = "form-control"})
            <br />
            <button type="submit" class="btn btn-info">Agregar Comentario</button>
        }
    </div>
}

<div id="comments-section" class="container bg-light">
    <h5 class="text-black-50 fw-bold">Comentarios</h5>
    @foreach (var items in Model.listValoracion)
    {
        <div id="comentario">
            @items.UsuarioId
            <div>
                <input id="input-21e" value="@items.Valoracion1" type="text" class="rating" data-theme="krajee-fas" data-min=0 data-max=5 data-step=1 data-size="xs" title="" disabled>
            </div>
            @items.Comentario
        </div>
    }
</div>